kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hyperv-csi-node-role
  labels:
    app.kubernetes.io/name: hyperv-csi-driver
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "patch"]
  # - apiGroups: ["storage.k8s.io"]
  #   resources: ["volumeattachments"]
  #   verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get"]
