kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hyperv-csi-node-getter-binding
  labels:
    app.kubernetes.io/name: hyperv-csi-driver
subjects:
  - kind: ServiceAccount
    name: hyperv-csi-node-sa
roleRef:
  kind: ClusterRole
  name: hyperv-csi-node-role
  apiGroup: rbac.authorization.k8s.io
