kind: Deployment
apiVersion: apps/v1
metadata:
  name: hyperv-csi-controller
  labels:
    app.kubernetes.io/name: hyperv-csi-driver
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: hyperv-csi-controller
      app.kubernetes.io/name: hyperv-csi-driver
  template:
    metadata:
      labels:
        app: hyperv-csi-controller
        app.kubernetes.io/name: hyperv-csi-driver
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: hyperv-csi-controller-sa
      priorityClassName: system-cluster-critical
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoExecute
          operator: Exists
          tolerationSeconds: 300
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: hyperv-plugin
          image: nhduc2001kt/hyperv-csi-driver:0.1.0
          imagePullPolicy: Always # TODO: change this
          # command:
          #   - sleep
          # args:
          #   - infinity
          args:
            - controller
            - --endpoint=$(CSI_ENDPOINT)
            - --winrm-user=Administrator
            - --winrm-password=Abcd!1234
            - --winrm-host=10.211.55.4
            - --winrm-allow-insecure
            - --v=5
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
            - name: CSI_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
            - name: tmp-dir
              mountPath: /tmp
          ports:
            - name: healthz
              containerPort: 9808
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: healthz
          #   initialDelaySeconds: 10
          #   timeoutSeconds: 3
          #   periodSeconds: 10
          #   failureThreshold: 5
          # readinessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: healthz
          #   initialDelaySeconds: 10
          #   timeoutSeconds: 3
          #   periodSeconds: 10
          #   failureThreshold: 5
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 40Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
        - name: csi-provisioner
          image: gcr.io/k8s-staging-sig-storage/csi-provisioner:canary
          imagePullPolicy: IfNotPresent
          args:
            - --timeout=60s
            - --csi-address=$(ADDRESS)
            - --v=4
            # - --feature-gates=Topology=true
            - --extra-create-metadata
            - --leader-election=true
            # - --default-fstype=ext4
            - --kube-api-qps=20
            - --kube-api-burst=100
            - --worker-threads=100
            - --retry-interval-max=30m
            # - --feature-gates=VolumeAttributesClass=true
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 40Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
        - name: csi-attacher
          image: gcr.io/k8s-staging-sig-storage/csi-attacher:canary
          imagePullPolicy: IfNotPresent
          args:
            - --timeout=60s
            - --csi-address=$(ADDRESS)
            - --v=2
            - --leader-election=true
            - --kube-api-qps=20
            - --kube-api-burst=100
            - --worker-threads=100
            - --retry-interval-max=5m
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 40Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
        # - name: csi-snapshotter
        #   image: public.ecr.aws/eks-distro/kubernetes-csi/external-snapshotter/csi-snapshotter:v8.1.0-eks-1-32-1
        #   imagePullPolicy: IfNotPresent
        #   args:
        #     - --csi-address=$(ADDRESS)
        #     - --leader-election=true
        #     - --v=2
        #     - --extra-create-metadata
        #     - --kube-api-qps=20
        #     - --kube-api-burst=100
        #     - --worker-threads=100
        #     - --retry-interval-max=30m
        #   env:
        #     - name: ADDRESS
        #       value: /var/lib/csi/sockets/pluginproxy/csi.sock
        #   volumeMounts:
        #     - name: socket-dir
        #       mountPath: /var/lib/csi/sockets/pluginproxy/
        #   resources:
        #     limits:
        #       memory: 256Mi
        #     requests:
        #       cpu: 10m
        #       memory: 40Mi
        #   securityContext:
        #     allowPrivilegeEscalation: false
        #     readOnlyRootFilesystem: true
        #     seccompProfile:
        #       type: RuntimeDefault
        # - name: csi-resizer
        #   image: public.ecr.aws/eks-distro/kubernetes-csi/external-resizer:v1.12.0-eks-1-32-1
        #   imagePullPolicy: IfNotPresent
        #   args:
        #     - --timeout=60s
        #     - --csi-address=$(ADDRESS)
        #     - --v=2
        #     - --handle-volume-inuse-error=false
        #     - --leader-election=true
        #     - --kube-api-qps=20
        #     - --kube-api-burst=100
        #     - --workers=100
        #     - --retry-interval-max=30m
        #     - --feature-gates=VolumeAttributesClass=true
        #   env:
        #     - name: ADDRESS
        #       value: /var/lib/csi/sockets/pluginproxy/csi.sock
        #   volumeMounts:
        #     - name: socket-dir
        #       mountPath: /var/lib/csi/sockets/pluginproxy/
        #   resources:
        #     limits:
        #       memory: 256Mi
        #     requests:
        #       cpu: 10m
        #       memory: 40Mi
        #   securityContext:
        #     allowPrivilegeEscalation: false
        #     readOnlyRootFilesystem: true
        #     seccompProfile:
        #       type: RuntimeDefault
        # - name: liveness-probe
        #   image: public.ecr.aws/eks-distro/kubernetes-csi/livenessprobe:v2.14.0-eks-1-32-1
        #   imagePullPolicy: IfNotPresent
        #   args:
        #     - --csi-address=/csi/csi.sock
        #   volumeMounts:
        #     - name: socket-dir
        #       mountPath: /csi
        #   resources:
        #     limits:
        #       memory: 256Mi
        #     requests:
        #       cpu: 10m
        #       memory: 40Mi
        #   securityContext:
        #     allowPrivilegeEscalation: false
        #     readOnlyRootFilesystem: true
      volumes:
        - name: socket-dir
          emptyDir: {}
        - name: tmp-dir
          emptyDir: {}
