apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: hyperv.csi.k8s.io
  labels:
    app.kubernetes.io/name: hyperv-csi-driver
spec:
  attachRequired: true
  podInfoOnMount: false
  fsGroupPolicy: File
