kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: hyperv-csi-node
  labels:
    app.kubernetes.io/name: hyperv-csi-driver
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hyperv-csi-node
      app.kubernetes.io/name: hyperv-csi-driver
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 10%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hyperv-csi-node
        app.kubernetes.io/name: hyperv-csi-driver
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: hyperv-csi-node-sa
      terminationGracePeriodSeconds: 30
      priorityClassName: system-node-critical
      tolerations:
        - operator: Exists
      hostNetwork: false
      securityContext:
        fsGroup: 0
        runAsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
      containers:
        - name: hyperv-kvp-daemon
          image: nhduc2001kt/hv-kvp-daemon:ubuntu-25.04
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: hyperv-metadata-dir
              mountPath: /var/lib/hyperv
          securityContext:
            privileged: true
        - name: hyperv-plugin
          image: nhduc2001kt/hyperv-csi-driver:0.1.0
          imagePullPolicy: Always
          args:
            - node
            - --endpoint=$(CSI_ENDPOINT)
            # - --csi-mount-point-prefix=/var/lib/kubelet/plugins/kubernetes.io/csi/hyperv.csi.k8s.io/
            - --logging-format=text
            - --v=2
          env:
            - name: CSI_ENDPOINT
              value: unix:/csi/csi.sock
            - name: CSI_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: kubelet-dir
              mountPath: /var/lib/kubelet
              mountPropagation: "Bidirectional"
            - name: plugin-dir
              mountPath: /csi
            - name: device-dir
              mountPath: /dev
            - name: hyperv-metadata-dir
              mountPath: /var/lib/hyperv
          ports:
            - name: healthz
              containerPort: 9808
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: healthz
          #   initialDelaySeconds: 10
          #   timeoutSeconds: 3
          #   periodSeconds: 10
          #   failureThreshold: 5
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 40Mi
          securityContext:
            privileged: true
            readOnlyRootFilesystem: true
          # lifecycle:
          #   preStop:
          #     exec:
          #       command: ["/bin/hyperv-csi-driver", "pre-stop-hook"]
        - name: node-driver-registrar
          image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.13.0
          imagePullPolicy: IfNotPresent
          args:
            - --csi-address=$(ADDRESS)
            - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
            - --v=2
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /var/lib/kubelet/plugins/hyperv.csi.k8s.io/csi.sock
          livenessProbe:
            exec:
              command:
                - /csi-node-driver-registrar
                - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
                - --mode=kubelet-registration-probe
            initialDelaySeconds: 30
            periodSeconds: 90
            timeoutSeconds: 15
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
            - name: probe-dir
              mountPath: /var/lib/kubelet/plugins/hyperv.csi.k8s.io/
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 40Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
        # - name: liveness-probe
        #   image: public.ecr.aws/eks-distro/kubernetes-csi/livenessprobe:v2.14.0-eks-1-32-1
        #   imagePullPolicy: IfNotPresent
        #   args:
        #     - --csi-address=/csi/csi.sock
        #   volumeMounts:
        #     - name: plugin-dir
        #       mountPath: /csi
        #   resources:
        #     limits:
        #       memory: 256Mi
        #     requests:
        #       cpu: 10m
        #       memory: 40Mi
        #   securityContext:
        #     allowPrivilegeEscalation: false
        #     readOnlyRootFilesystem: true
      volumes:
        - name: hyperv-metadata-dir
          hostPath:
            path: /var/lib/hyperv
            type: DirectoryOrCreate
        - name: kubelet-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/hyperv.csi.k8s.io/
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory
        - name: device-dir
          hostPath:
            path: /dev
            type: Directory
        - name: probe-dir
          emptyDir: {}
