kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hyperv-csi-leases-rolebinding
  labels:
    app.kubernetes.io/name: hyperv-csi-driver
subjects:
- kind: ServiceAccount
  name: hyperv-csi-controller-sa
roleRef:
  kind: Role
  name: hyperv-csi-leases-role
  apiGroup: rbac.authorization.k8s.io
