apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  - target:
      kind: Secret
      name: winrm-credentials
    patch: |-
      - op: replace
        path: /data/WINRM_USER
        value:  # <------------------------------ Use your own user
      - op: replace
        path: /data/WINRM_PASSWORD
        value:  # <------------------------------ Use your own password
  - target:
      kind: ConfigMap
      name: winrm-configs
    patch: |-
      - op: replace
        path: /data/WINRM_HOST
        value:  # <------------------------------ Use your own host