apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hyperv-pvc
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: hyperv-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
