apiVersion: v1
kind: PersistentVolume
metadata:
  name: hyperv-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    driver: hyperv.csi.k8s.io
    fsType: ext4
    volumeHandle: C:\ProgramData\Microsoft\Windows\Virtual Hard Disks\test.vhdx
