apiVersion: v1
kind: PersistentVolume
metadata:
  name: hyperv-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    driver: hyperv.csi.k8s.io
    fsType: ext4
    volumeHandle: vol-03c604538dd7d2f41
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #       - matchExpressions:
  #           - key: topology.kubernetes.io/zone
  #             operator: In
  #             values:
  #               - us-east-2c
